---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-kubedoom
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: my-kubedoom
  template:
    metadata:
      labels:
        app: my-kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: kubedoom-game
        ports:
        - containerPort: 5900
          protocol: TCP  
