---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-hdd-gz1

